export const PALETTES = [
  // ─── MINIMAL LIGHT (النهاري المعتمد) ───
  {
    id: 'studio-graphite',
    name: 'أبيض استوديو (جرافيت مينيمال)',
    nameEn: 'Clean Studio (Graphite Minimal)',
    mode: 'light',
    badge: 'النهاري المعتمد — أبيض ناصع مع أزرار جرافيت فخمة',
    preview: {
      bg: '#f8fafc',
      surface: '#ffffff',
      accent: '#0f172a',
      border: '#e2e8f0',
    },
    vars: {
      '--bg-base': '#f8fafc',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#f1f5f9',
      '--color-primary': '#0f172a',
      '--color-primary-hover': '#1e293b',
      '--color-primary-active': '#020617',
      '--text-primary': '#0f172a',
      '--text-muted': '#64748b',
      '--text-dim': '#94a3b8',
      '--text-inverted': '#ffffff',
      '--border-default': '#e2e8f0',
      '--border-subtle': '#f1f5f9',
      '--ac-bg': 'rgba(15, 23, 42, 0.08)',
      '--status-success': '#10b981',
      '--status-success-bg': 'rgba(16, 185, 129, 0.10)',
    },
  },
  {
    id: 'studio-clean',
    name: 'أبيض استوديو (أزرق ملكي)',
    nameEn: 'Clean Studio (Royal Blue)',
    mode: 'light',
    badge: 'أبيض ناصع مع أزرق تقني',
    preview: {
      bg: '#f8fafc',
      surface: '#ffffff',
      accent: '#2563eb',
      border: '#e2e8f0',
    },
    vars: {
      '--bg-base': '#f8fafc',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#f1f5f9',
      '--color-primary': '#2563eb',
      '--color-primary-hover': '#1d4ed8',
      '--color-primary-active': '#1e40af',
      '--text-primary': '#0f172a',
      '--text-muted': '#64748b',
      '--text-dim': '#94a3b8',
      '--text-inverted': '#ffffff',
      '--border-default': '#e2e8f0',
      '--border-subtle': '#f1f5f9',
      '--ac-bg': 'rgba(37, 99, 235, 0.10)',
      '--status-success': '#10b981',
      '--status-success-bg': 'rgba(16, 185, 129, 0.10)',
    },
  },
  {
    id: 'studio-emerald',
    name: 'أبيض استوديو (أخضر زمردي)',
    nameEn: 'Clean Studio (Emerald)',
    mode: 'light',
    badge: 'طبيعي وحيوي ومنعش',
    preview: {
      bg: '#f8fafc',
      surface: '#ffffff',
      accent: '#059669',
      border: '#e2e8f0',
    },
    vars: {
      '--bg-base': '#f8fafc',
      '--bg-surface': '#ffffff',
      '--bg-surface-elevated': '#f0fdf4',
      '--color-primary': '#059669',
      '--color-primary-hover': '#047857',
      '--color-primary-active': '#065f46',
      '--text-primary': '#0f172a',
      '--text-muted': '#64748b',
      '--text-dim': '#94a3b8',
      '--text-inverted': '#ffffff',
      '--border-default': '#e2e8f0',
      '--border-subtle': '#f1f5f9',
      '--ac-bg': 'rgba(5, 150, 105, 0.10)',
      '--status-success': '#059669',
      '--status-success-bg': 'rgba(5, 150, 105, 0.10)',
    },
  },

  // ─── BRAND NEW DEEP DARK LIST (الليستة الجديدة للداكن) ───
  {
    id: 'true-black-minimal',
    name: '1. أسود دارك خالص (True Pitch Black)',
    nameEn: 'True Pitch Black (OLED Minimal)',
    mode: 'dark',
    badge: 'الخيار الأول — أسود فاحم 100% بدون أي ألوان مشوشة',
    preview: {
      bg: '#000000',
      surface: '#0d0d0d',
      accent: '#ffffff',
      border: '#222222',
    },
    vars: {
      '--bg-base': '#000000',
      '--bg-surface': '#0d0d0d',
      '--bg-surface-elevated': '#171717',
      '--color-primary': '#ffffff',
      '--color-primary-hover': '#e5e5e5',
      '--color-primary-active': '#cccccc',
      '--text-primary': '#ffffff',
      '--text-muted': '#a1a1aa',
      '--text-dim': '#71717a',
      '--text-inverted': '#000000',
      '--border-default': '#222222',
      '--border-subtle': '#141414',
      '--ac-bg': 'rgba(255, 255, 255, 0.10)',
      '--status-success': '#22c55e',
      '--status-success-bg': 'rgba(34, 197, 94, 0.15)',
    },
  },
  {
    id: 'carbon-matte-black',
    name: '2. كربون مطفأ (Carbon Matte Black)',
    nameEn: 'Carbon Matte Black & Silver',
    mode: 'dark',
    badge: 'أسود كربون مطفأ مع حواف وفواصل ناعمة',
    preview: {
      bg: '#080808',
      surface: '#121212',
      accent: '#e4e4e7',
      border: '#262626',
    },
    vars: {
      '--bg-base': '#080808',
      '--bg-surface': '#121212',
      '--bg-surface-elevated': '#1c1c1c',
      '--color-primary': '#e4e4e7',
      '--color-primary-hover': '#ffffff',
      '--color-primary-active': '#d4d4d8',
      '--text-primary': '#f4f4f5',
      '--text-muted': '#a1a1aa',
      '--text-dim': '#52525b',
      '--text-inverted': '#080808',
      '--border-default': '#262626',
      '--border-subtle': '#181818',
      '--ac-bg': 'rgba(228, 228, 231, 0.12)',
      '--status-success': '#10b981',
      '--status-success-bg': 'rgba(16, 185, 129, 0.15)',
    },
  },
  {
    id: 'obsidian-graphite-deep',
    name: '3. أوبسيديان فحم عميق (Obsidian Deep)',
    nameEn: 'Obsidian Deep Charcoal',
    mode: 'dark',
    badge: 'فحمي عميق جداً هادئ وأنيق',
    preview: {
      bg: '#0a0c10',
      surface: '#12151b',
      accent: '#f8fafc',
      border: '#212631',
    },
    vars: {
      '--bg-base': '#0a0c10',
      '--bg-surface': '#12151b',
      '--bg-surface-elevated': '#1a1e27',
      '--color-primary': '#f8fafc',
      '--color-primary-hover': '#ffffff',
      '--color-primary-active': '#e2e8f0',
      '--text-primary': '#f8fafc',
      '--text-muted': '#94a3b8',
      '--text-dim': '#64748b',
      '--text-inverted': '#0a0c10',
      '--border-default': '#212631',
      '--border-subtle': '#161920',
      '--ac-bg': 'rgba(248, 250, 252, 0.12)',
      '--status-success': '#10b981',
      '--status-success-bg': 'rgba(16, 185, 129, 0.15)',
    },
  },
  {
    id: 'jet-black-emerald',
    name: '4. أسود فاحم وزمردي (Jet Black & Mint)',
    nameEn: 'Jet Black & Vivid Mint',
    mode: 'dark',
    badge: 'سواد خالص مع أزرار خضراء ناصعة',
    preview: {
      bg: '#000000',
      surface: '#0c0c0c',
      accent: '#10b981',
      border: '#202020',
    },
    vars: {
      '--bg-base': '#000000',
      '--bg-surface': '#0c0c0c',
      '--bg-surface-elevated': '#161616',
      '--color-primary': '#10b981',
      '--color-primary-hover': '#059669',
      '--color-primary-active': '#047857',
      '--text-primary': '#ffffff',
      '--text-muted': '#a1a1aa',
      '--text-dim': '#71717a',
      '--text-inverted': '#000000',
      '--border-default': '#202020',
      '--border-subtle': '#141414',
      '--ac-bg': 'rgba(16, 185, 129, 0.15)',
      '--status-success': '#10b981',
      '--status-success-bg': 'rgba(16, 185, 129, 0.15)',
    },
  },
  {
    id: 'pitch-black-amber',
    name: '5. أسود فاحم وعنبري (Pitch Black & Gold)',
    nameEn: 'Pitch Black & Roasted Gold',
    mode: 'dark',
    badge: 'سواد خالص مع أزرار عنبرية دافئة للمطاعم',
    preview: {
      bg: '#000000',
      surface: '#0e0e0e',
      accent: '#f59e0b',
      border: '#242424',
    },
    vars: {
      '--bg-base': '#000000',
      '--bg-surface': '#0e0e0e',
      '--bg-surface-elevated': '#181818',
      '--color-primary': '#f59e0b',
      '--color-primary-hover': '#d97706',
      '--color-primary-active': '#b45309',
      '--text-primary': '#ffffff',
      '--text-muted': '#a3a3a3',
      '--text-dim': '#737373',
      '--text-inverted': '#000000',
      '--border-default': '#242424',
      '--border-subtle': '#161616',
      '--ac-bg': 'rgba(245, 158, 11, 0.15)',
      '--status-success': '#10b981',
      '--status-success-bg': 'rgba(16, 185, 129, 0.15)',
    },
  },
  {
    id: 'titanium-smoke-dark',
    name: '6. تيتانيوم رمادي داكن (Titanium Dark)',
    nameEn: 'Titanium Dark & Soft Cyan',
    mode: 'dark',
    badge: 'رمادي تيتانيوم معدني مريح جداً للبصر',
    preview: {
      bg: '#0d0f12',
      surface: '#15191e',
      accent: '#38bdf8',
      border: '#252b35',
    },
    vars: {
      '--bg-base': '#0d0f12',
      '--bg-surface': '#15191e',
      '--bg-surface-elevated': '#1d232c',
      '--color-primary': '#38bdf8',
      '--color-primary-hover': '#0ea5e9',
      '--color-primary-active': '#0284c7',
      '--text-primary': '#f1f5f9',
      '--text-muted': '#94a3b8',
      '--text-dim': '#64748b',
      '--text-inverted': '#0d0f12',
      '--border-default': '#252b35',
      '--border-subtle': '#191d24',
      '--ac-bg': 'rgba(56, 189, 248, 0.15)',
      '--status-success': '#38bdf8',
      '--status-success-bg': 'rgba(56, 189, 248, 0.15)',
    },
  },
];
